pool:
  name: Azure Pipelines
  vmImage: windows-2019
  demands:
  - msbuild
  - visualstudio
  - vstest

trigger: none

pr:
- main
- dev

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: restore
    projects: 'CustomTextAnalytics.CLUtils\Solution\CogSLanguageUtilities.sln'
    vstsFeed: '87f61c68-a88c-4f2d-a649-603761ef80ac'

- task: VSBuild@1
  displayName: 'Build solution CustomTextAnalytics.CLUtils\Solution\CogSLanguageUtilities.sln'
  inputs:
    solution: 'CustomTextAnalytics.CLUtils\Solution\CogSLanguageUtilities.sln'
    msbuildArgs: '/m /v:q'
    platform: '$(BuildPlatform)'
    configuration: '$(BuildConfiguration)'
    msbuildArchitecture: x64
    clean: true

- task: VSTest@2
  displayName: 'Run Tests'
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      CustomTextAnalytics.CLUtils\Solution\CogSLanguageUtilities.Tests\bin\Release\**\CogSLanguageUtilities.Tests.dll
      CustomTextAnalytics.CLUtils\Solution\LuisModelEvaluation\LuisModelEvaluation.Tests\bin\Release\**\LuisModelEvaluation.Tests.dll
    searchFolder: '$(System.DefaultWorkingDirectory)'
    testFiltercriteria: 'FullyQualifiedName~Unit'
    runInParallel: false
    codeCoverageEnabled: false
    otherConsoleOptions: '/Framework:.NETCoreApp,Version=v3.1 /platform:x64'
    platform: 'x64'
  env:
    CUSTOM_TEXT_APP_ID: $(custom.text.app.id)
    CUSTOM_TEXT_ENDPOINT: $(custom.text.endpoint)
    CUSTOM_TEXT_KEY: $(custom.text.key)
    MSREAD_COGNITIVE_SERVICES_ENDPOINT: $(msread.cognitive.services.endpoint)
    MSREAD_COGNITIVE_SERVICES_KEY: $(msread.cognitive.services.key)
    STORAGE_ACCOUNT_CONNECTION_STRING: $(storage.account.connection.string)
    TEXT_ANALYTICS_ENDPOINT: $(msread.cognitive.services.endpoint)
    TEXT_ANALYTICS_KEY: $(msread.cognitive.services.key)